"""empty message

Revision ID: 2de0b851a904
Revises: 87b9c72ea953
Create Date: 2017-05-25 11:01:25.014000

"""

# revision identifiers, used by Alembic.
revision = '2de0b851a904'
down_revision = '87b9c72ea953'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('remaining_coverage', sa.Numeric(precision=15, scale=12), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'remaining_coverage')
    ### end Alembic commands ###
