"""empty message

Revision ID: 59bb7334398b
Revises: 9b213a1d1e07
Create Date: 2017-06-04 13:04:29.368000

"""

# revision identifiers, used by Alembic.
revision = '59bb7334398b'
down_revision = '9b213a1d1e07'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('is_open', sa.Boolean(), nullable=True))
    op.add_column('outcome', sa.Column('type_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_outcome_type_id'), 'outcome', ['type_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outcome_type_id'), table_name='outcome')
    op.drop_column('outcome', 'type_id')
    op.drop_column('event', 'is_open')
    ### end Alembic commands ###
