"""empty message

Revision ID: 6c9c24478477
Revises: e429cc1bd606
Create Date: 2017-06-04 17:01:45.836000

"""

# revision identifiers, used by Alembic.
revision = '6c9c24478477'
down_revision = 'e429cc1bd606'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'bid_tx_hash_key', 'bid', type_='unique')
    op.drop_constraint(u'offer_tx_hash_key', 'offer', type_='unique')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'offer_tx_hash_key', 'offer', ['tx_hash'])
    op.create_unique_constraint(u'bid_tx_hash_key', 'bid', ['tx_hash'])
    ### end Alembic commands ###
