"""empty message

Revision ID: 72bb4bf6614e
Revises: 97f43bc81200
Create Date: 2017-05-26 19:52:38.497000

"""

# revision identifiers, used by Alembic.
revision = '72bb4bf6614e'
down_revision = '97f43bc81200'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('hash', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'offer', ['hash'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='unique')
    op.drop_column('offer', 'hash')
    ### end Alembic commands ###
