"""empty message

Revision ID: 754d8eee7687
Revises: 02ea504bcf58
Create Date: 2017-05-20 15:21:37.161000

"""

# revision identifiers, used by Alembic.
revision = '754d8eee7687'
down_revision = '02ea504bcf58'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('guid', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'event', ['guid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='unique')
    op.drop_column('event', 'guid')
    ### end Alembic commands ###
