"""empty message

Revision ID: 87b9c72ea953
Revises: 754d8eee7687
Create Date: 2017-05-22 17:00:28.918000

"""

# revision identifiers, used by Alembic.
revision = '87b9c72ea953'
down_revision = '754d8eee7687'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
