"""empty message

Revision ID: 8f44375cb8d5
Revises: None
Create Date: 2017-05-19 10:06:58.175000

"""

# revision identifiers, used by Alembic.
revision = '8f44375cb8d5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
