"""empty message

Revision ID: 97f43bc81200
Revises: 2de0b851a904
Create Date: 2017-05-25 21:09:41.836000

"""

# revision identifiers, used by Alembic.
revision = '97f43bc81200'
down_revision = '2de0b851a904'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_bid_offer_id'), 'bid', ['offer_id'], unique=False)
    op.create_index(op.f('ix_bid_user_id'), 'bid', ['user_id'], unique=False)
    op.create_index(op.f('ix_event_guid'), 'event', ['guid'], unique=True)
    op.drop_constraint(u'event_guid_key', 'event', type_='unique')
    op.create_index(op.f('ix_offer_outcome_id'), 'offer', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_offer_user_id'), 'offer', ['user_id'], unique=False)
    op.create_index(op.f('ix_outcome_event_id'), 'outcome', ['event_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outcome_event_id'), table_name='outcome')
    op.drop_index(op.f('ix_offer_user_id'), table_name='offer')
    op.drop_index(op.f('ix_offer_outcome_id'), table_name='offer')
    op.create_unique_constraint(u'event_guid_key', 'event', ['guid'])
    op.drop_index(op.f('ix_event_guid'), table_name='event')
    op.drop_index(op.f('ix_bid_user_id'), table_name='bid')
    op.drop_index(op.f('ix_bid_offer_id'), table_name='bid')
    ### end Alembic commands ###
