"""empty message

Revision ID: 9b213a1d1e07
Revises: 72bb4bf6614e
Create Date: 2017-06-02 18:47:02.468000

"""

# revision identifiers, used by Alembic.
revision = '9b213a1d1e07'
down_revision = '72bb4bf6614e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bid', sa.Column('hash', sa.String(length=255), nullable=True))
    op.add_column('bid', sa.Column('tx_hash', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'bid', ['tx_hash'])
    op.create_unique_constraint(None, 'bid', ['hash'])
    op.add_column('offer', sa.Column('tx_hash', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'offer', ['tx_hash'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offer', type_='unique')
    op.drop_column('offer', 'tx_hash')
    op.drop_constraint(None, 'bid', type_='unique')
    op.drop_constraint(None, 'bid', type_='unique')
    op.drop_column('bid', 'tx_hash')
    op.drop_column('bid', 'hash')
    ### end Alembic commands ###
