"""empty message

Revision ID: d0068ed3fba8
Revises: 652b467d2cb6
Create Date: 2017-05-20 13:00:03.623000

"""

# revision identifiers, used by Alembic.
revision = 'd0068ed3fba8'
down_revision = '652b467d2cb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escrow',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('bid_id', sa.Integer(), nullable=True),
    sa.Column('wallet_id', sa.Integer(), nullable=True),
    sa.Column('comission', sa.Numeric(precision=15), nullable=True),
    sa.Column('value', sa.Numeric(precision=15), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('payout_date', sa.DateTime(), nullable=True),
    sa.Column('incoming_hash', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bid_id'], ['bid.id'], ),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'wallet', sa.Column('guid', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'wallet', ['guid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wallet', type_='unique')
    op.drop_column(u'wallet', 'guid')
    op.drop_table('escrow')
    ### end Alembic commands ###
