"""empty message

Revision ID: e429cc1bd606
Revises: 59bb7334398b
Create Date: 2017-06-04 13:33:21.863000

"""

# revision identifiers, used by Alembic.
revision = 'e429cc1bd606'
down_revision = '59bb7334398b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('is_win', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offer', 'is_win')
    ### end Alembic commands ###
